name: release

on:
  push:
    tags:
    - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
        run: |
          pip install tox
          tox -e tests,release,upload
